name: Build

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Node Environment
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '17.x'
      - name: Install project dependencies
        run: npm install
      - name: Build the project
        run: npm run build
